/// Flutter icons CustomApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomApp
///      fonts:
///       - asset: fonts/CustomApp.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomApp {
  CustomApp._();

  static const _kFontFam = 'CustomApp';
  static const String? _kFontPkg = null;

  static const IconData baseline_filter_list_24px =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseline_swap_vert_24px =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
